config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :popup_contact_forms
  resources :contact_forms
  resources :items
  resources :articles
  resources :descriptions
  resources :pictures

  scope "(:locale)", :locale => /en|ru/ do 
  root 'static_pages#home'
  match '/',        to: 'static_pages#home',       via: 'post'
  match '/manager', to: 'static_pages#manager',    via: 'get'
  match '/manager', to: 'static_pages#manager',    via: 'post'
  match '/signin',  to: 'sessions#new',            via: 'get'
  match '/signout', to: 'sessions#destroy',        via: 'delete'
  match '/manager', to: 'static_pages#manager',    via: 'edit'
  match '/manager', to: 'static_pages#manager',    via: 'update'
end

   

end

app/models/article.rb
class Article < ActiveRecord::Base
	translates :title, :text
end

app/models/contact_form.rb
class ContactForm < ActiveRecord::Base
	validates :name, presence: true, length: { maximum: 20 }
	validates :email, presence: true, length: { maximum: 20 }
	validates :phone, presence: true, length: { maximum: 20 }
	validates :text, presence: true, length: { maximum: 200 }
end

app/models/description.rb
class Description < ActiveRecord::Base
	translates :title, :text
end

app/models/item.rb
class Item < ActiveRecord::Base
	dragonfly_accessor :image
	translates :variable1, :variable2, :variable3, :variable4, :value1, :value2, 
			   :value3, :value4, :comment, :item_name
end

app/models/photo.rb
class Photo < ActiveRecord::Base
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	dragonfly_accessor :image
end

app/models/popup_contact_form.rb
class PopupContactForm < ActiveRecord::Base
	validates :name, :phone, presence: true, on: :create
end

app/models/user.rb
class User < ActiveRecord::Base
	before_create :create_remember_token
	validates :name, presence: true, uniqueness: true, length: { maximum: 10 }
	
  has_secure_password
  validates :password, length: { minimum: 6 }

	def User.new_remember_token
    	SecureRandom.urlsafe_base64
  	end

 	def User.encrypt(token)
    	Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def new
       @article = Article.new
    end

    def edit
  		@article = Article.find(params[:id])
	  end

    def create
    	@article = Article.new article_params
    	@article.save
    	redirect_to manager_path
    end

    def update
  		@article = Article.find(params[:id])

  		if @article.update(article_params)
    		redirect_to manager_path
  		else
    		render 'edit'
  		end
	  end

    private

    def article_params
       params.require(:article).permit(:title, :text)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	  def new
       @item = Item.new
    end
    
    def edit
        @item = Item.find(params[:id])
    end

    def create
       @item = Item.new item_params
       if @item.save
        flash[:success] = "Товар успешно добавлен!"
        redirect_to manager_path
       else
        flash[:error] = "Что-то пошло не так... Возможно, Вы не добавили фотографию?"
        redirect_to manager_path
       end
       
    end

    def update
      @item = Item.find(params[:id])

      if @item.update(item_params)
        redirect_to manager_path
      else
        render 'edit'
      end
    end

    def destroy
 		 @item = Item.find(params[:id])
 		 if @item.destroy
      flash[:success] = "Товар успешно Удален!"
     redirect_to manager_path
     else
      flash[:error] = "Что-то пошло не так..."
      redirect_to manager_path
     end
 	  end

    private

    def item_params
       params.require(:item).permit(:variable1, :variable2, :variable3, :variable4, :value1, :value2, :value3, :value4, :comment, :item_name, :price, :image)
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	  def new
       @picture = Picture.new
    end

    def edit
        @picture = Picture.find(params[:id])
    end

    def create
       @picture = Picture.new picture_params
       if @picture.save
          redirect_to manager_path
          flash[:success] = "Фотогалерея успешно обновлена!"
       else
        flash[:error] = "Что-то пошло не так... Возможно, Вы не добавили фотографию?"
        redirect_to manager_path
       end
    end

    def update
      @picture = Picture.find(params[:id])

      if @picture.update(picture_params)
        redirect_to manager_path
      else
        render 'edit'
      end
    end

    def destroy
 		@picture = Picture.find(params[:id])
 		if @picture.destroy
      flash[:success] = "Фотография успешно удалена."
     	redirect_to manager_path
    else
        flash[:error] = "Что-то пошло не так..."
        redirect_to manager_path
    end
 	end

    private

    def picture_params
       params.require(:picture).permit(:image)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to manager_path
      flash[:success] = 'Добро пожаловать!'
      # Sign the user in and redirect to the user's show page.
    else
      flash[:error] = 'Неправильный пароль либо логин. Попробуйте еще раз.'
      redirect_to signin_path
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/descriptions_helper.rb
module DescriptionsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/popup_contact_form_helper.rb
module PopupContactFormHelper
end

app/helpers/sessions_helper.rb
 module SessionsHelper

/  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end /

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in."
    end
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_show.html.erb
<div class = "container">
  <div class = "row col-lg-12">
  <hr>
    <h1>Блок 1 (сверху)</h1>
      <% @articles.each do |article| %>
        <%=raw article.text %>
        <%= link_to 'Изменить', edit_article_path(article) %>
      <% end %>
  </div>
</div>
<hr>

app/views/articles/edit.html.erb
<h1><%= t('article.edit') %></h1>
 
<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text, :class => "tinymce", :rows => 15, :cols => 80 %>
  </p>
  <%= f.submit "Сохранить" %>
<% end %>
 
<%= link_to 'Назад', manager_path %>
<%= tinymce %>

app/views/articles/index.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
    </tr>
  <% end %>
</table>

app/views/items/_edit.html.erb
<h2>Список товаров</h1>

<% @items.each do |item| %>
	<div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 paddings-2">
		<div class="goods-container">
    		<%= image_tag item.image.url if item.image_stored? %>
			<%= image_tag "line_3.png", class: "img-responsive img-properties" %>
			<div class="goods-name">
				<%= item.item_name %>	
			</div>
			<table class="goods-description">
				<tr>
					<tr><td><%= item.variable1 %>:</td><td><%= item.value1 %></td></tr>
					<tr><td><%= item.variable2 %>:</td><td><%= item.value2 %></td></tr>
					<tr><td><%= item.variable3 %>:</td><td><%= item.value3 %></td></tr>
					<tr><td><%= item.variable4 %>:</td><td><%= item.value4 %></td></tr>
				</tr>
			</table>
			<div class="row goods-description">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 font-small-size">
					<p><%= item.comment %></p>
				</div>
			</div>
		</div>
		<div class="col-lg-2">
	                  <%= link_to "Удалить", item, method: :delete,
	                                     data: { confirm: "Вы уверены?" }%>
	    </div>
		<div class="col-lg-1">
	    	<%= link_to 'Изменить', edit_item_path(item) %>
	    </div>
	</div>
<% end %>

app/views/items/_index.html.erb
<h1>Список товаров</h1>
<% @items.each do |item| %>
	<div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 paddings-2">
		<div class="goods-container">
    		<%= image_tag item.image.url if item.image_stored? %>
			<%= image_tag "line_3.png", class: "img-responsive img-properties" %>
			<div class="goods-name">
				<%= item.item_name %>	
			</div>
			<table class="goods-description">
				<tr>
					<tr><td><%= item.variable1 %>:</td><td><%= item.value1 %></td></tr>
					<tr><td><%= item.variable2 %>:</td><td><%= item.value2 %></td></tr>
					<tr><td><%= item.variable3 %>:</td><td><%= item.value3 %></td></tr>
					<tr><td><%= item.variable4 %>:</td><td><%= item.value4 %></td></tr>
				</tr>
			</table>
			<div class="row goods-description">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 font-small-size">
					<p><%= item.comment %></p>
				</div>
			</div>
		</div>
		<div class="col-lg-4">
	                  <%= link_to "Удалить", item, method: :delete,
	                                     data: { confirm: "Вы уверены?" }%>
	    </div>
		<div class="col-lg-1">
	    	<%= link_to 'Изменить', edit_item_path(item) %>
	    </div>
	</div>
<% end %>

app/views/items/_new.html.erb
<h1><%= t('item.new') %></h1>
<%= form_for @item do |f| %>
      <div class="container">
         <div class="row col-lg-12">
            <div class="col-lg-2">
               <%= f.label "Название" %>
            </div>
            <div class="col-lg-3 form-group img-radius">
               <%= f.text_field :item_name %>
            </div>
         </div>
      </div>

      <div class="container">
         <div class="row col-lg-12">
            <div class="col-lg-2">
               <%= f.label "Характеристика 1" %>
            </div>
            <div class="col-lg-3 form-group img-radius">
               <%= f.text_field :variable1 %>
            </div>
            <div class="col-lg-2 form-group">
               <%= f.label "Значение 1" %>
            </div>
            <div class="col-lg-3 form-group img-radius">
               <%= f.text_field :value1 %>
            </div>
         </div>
            <div class="row col-lg-12">
               <div class="col-lg-2 form-group">
                  <%= f.label "Характеристика 2" %>
               </div>
               <div class="col-lg-3 form-group img-radius">
                  <%= f.text_field :variable2 %>
               </div>
               <div class="col-lg-2 form-group">
                  <%= f.label "Значение 2" %>
               </div>
               <div class="col-lg-3 form-group img-radius">
                  <%= f.text_field :value2 %>
               </div>
         </div>
      </div>

      <div class="container">
         <div class="row col-lg-12">
            <div class="col-lg-2 form-group">
               <%= f.label "Характеристика 3" %>
            </div>
            <div class="col-lg-3 form-group img-radius">
               <%= f.text_field :variable3 %>
            </div>
            <div class="col-lg-2 form-group">
               <%= f.label "Значение 3" %>
            </div>
            <div class="col-lg-3 form-group img-radius">
               <%= f.text_field :value3 %>
            </div>
         </div>
      </div>

      <div class="container">
         <div class="row col-lg-12">
            <div class="col-lg-2 form-group">
               <%= f.label "Характеристика 4" %>
            </div>
            <div class="col-lg-3 form-group img-radius">
               <%= f.text_field :variable4 %>
            </div>
            <div class="col-lg-2 form-group">
               <%= f.label "Значение 4" %>
            </div>
            <div class="col-lg-3 form-group img-radius">
               <%= f.text_field :value4 %>
            </div>
         </div>
      </div>

      <div class="container">
         <div class="row col-lg-12">
            <div class="col-lg-2 form-group">
                  <%= f.label "Комментарий" %>
            </div>
            <div class="col-lg-3 form-group img-properties-radius">
                  <%= f.text_field :comment %>
            </div>
            <div class="col-lg-2 form-group">
                  <%= f.label "Цена, руб" %>
            </div>
            <div class="col-lg-3 form-group img-properties-radius">
                  <%= f.text_field :price %>
            </div>
         </div>   
      </div>

      <div class="container">
         <div class="row col-lg-12">
            <div class="col-lg-3">
                  <%= f.label "Изображение (400x300 pix)" %><%= f.file_field :image %>
            </div>
         </div>   
      </div>

      <div class="container">
         <div class="row col-lg-12">
            <div class="col-lg-2">
               <%= f.submit "Cоздать товар", class: "btn btn-large btn-primary" %> 
            </div> 
         </div>  
      </div>
<% end %>
<hr>

app/views/items/_show.html.erb
<div class="container" style="float: none">
	<div class="row " style="float: none">
		<% @items.each do |item| %>
			<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 paddings-2">
				<div class="goods-container">
					<%= image_tag item.image.url,  class: "img-responsive img-properties img-properties-radius" %>
					<%= image_tag "line_3.png", class: "img-responsive img-properties" %>
					<div class="goods-name">
						<%= item.item_name %>	
					</div>
					<table class="goods-description">
						<tr>
							<tr><td><%= item.variable1 %>:</td><td><%= item.value1 %></td></tr>
							<tr><td><%= item.variable2 %>:</td><td><%= item.value2 %></td></tr>
							<tr><td><%= item.variable3 %>:</td><td><%= item.value3 %></td></tr>
							<tr><td><%= item.variable4 %>:</td><td><%= item.value4 %></td></tr>
						</tr>
					</table>
					<div class="row goods-description">
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 font-small-size">
							<p><%= item.comment %></p>
						</div>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/items/edit.html.erb
<h1><%= t('item.edit') %></h1> 
 
<%= form_for :item, url: item_path(@item), method: :patch do |f| %>
      <div class="container">
         <div class="row col-lg-12">
            <div class="col-lg-2">
               <%= f.label "Название" %>
            </div>
            <div class="col-lg-3 form-group img-radius">
               <%= f.text_field :item_name %>
            </div>
         </div>
      </div>

      <div class="container">
         <div class="row col-lg-12">
            <div class="col-lg-2">
               <%= f.label "Характеристика 1" %>
            </div>
            <div class="col-lg-3 form-group img-radius">
               <%= f.text_field :variable1 %>
            </div>
            <div class="col-lg-2 form-group">
               <%= f.label "Значение 1" %>
            </div>
            <div class="col-lg-3 form-group img-radius">
               <%= f.text_field :value1 %>
            </div>
         </div>
            <div class="row col-lg-12">
               <div class="col-lg-2 form-group">
                  <%= f.label "Характеристика 2" %>
               </div>
               <div class="col-lg-3 form-group img-radius">
                  <%= f.text_field :variable2 %>
               </div>
               <div class="col-lg-2 form-group">
                  <%= f.label "Значение 2" %>
               </div>
               <div class="col-lg-3 form-group img-radius">
                  <%= f.text_field :value2 %>
               </div>
         </div>
      </div>

      <div class="container">
         <div class="row col-lg-12">
            <div class="col-lg-2 form-group">
               <%= f.label "Характеристика 3" %>
            </div>
            <div class="col-lg-3 form-group img-radius">
               <%= f.text_field :variable3 %>
            </div>
            <div class="col-lg-2 form-group">
               <%= f.label "Значение 3" %>
            </div>
            <div class="col-lg-3 form-group img-radius">
               <%= f.text_field :value3 %>
            </div>
         </div>
      </div>

      <div class="container">
         <div class="row col-lg-12">
            <div class="col-lg-2 form-group">
               <%= f.label "Характеристика 4" %>
            </div>
            <div class="col-lg-3 form-group img-radius">
               <%= f.text_field :variable4 %>
            </div>
            <div class="col-lg-2 form-group">
               <%= f.label "Значение 4" %>
            </div>
            <div class="col-lg-3 form-group img-radius">
               <%= f.text_field :value4 %>
            </div>
         </div>
      </div>

      <div class="container">
         <div class="row col-lg-12">
            <div class="col-lg-2 form-group">
                  <%= f.label "Комментарий" %>
            </div>
            <div class="col-lg-3 form-group img-properties-radius">
                  <%= f.text_field :comment %>
            </div>
            <div class="col-lg-2 form-group">
                  <%= f.label "Цена, руб" %>
            </div>
            <div class="col-lg-3 form-group img-properties-radius">
                  <%= f.text_field :price %>
            </div>
         </div>   
      </div>

      <div class="container">
         <div class="row col-lg-12">
            <div class="col-lg-3">
                  <%= f.label "Изображение (400x300 pix)" %><%= f.file_field :image %>
            </div>
         </div>   
      </div>
  <%= f.submit "Сохранить" %>
<% end %>
 
<%= link_to 'Назад', manager_path %>

app/views/pictures/_index.html.erb
<div class = "container">
  <div class = "row col-lg-12">
	<h2>Фотогалерея</h1>
	<% @pictures.each do |picture| %>
		<div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 paddings-2">
			<div class="goods-container">
	    		<%= image_tag picture.image.url if picture.image_stored? %>
			</div>
			<div class="col-lg-4">
		                  <%= link_to "Удалить", picture, method: :delete,
		                                     data: { confirm: "Вы уверены?" }%>
		    </div>
			<div class="col-lg-1">
		    	<%= link_to 'Изменить', edit_picture_path(picture) %>
		    </div>
		</div>
	<% end %>
  </div>
</div>

app/views/pictures/_new.html.erb
<div class="row col-lg-12">
<h1>Добавление изображений в фотогалерею</h1>
<%= form_for Picture.new do |f| %>
      <div class="container">
         <div class="row col-lg-12">
            <div class="col-lg-3">
                  <%= f.label "Изображение" %><%= f.file_field :image %>
            </div>
         </div>   
      </div>

      <div class="container">
         <div class="row col-lg-12">
            <div class="col-lg-2">
               <%= f.submit "Добавить изображение", class: "btn btn-large btn-primary" %> 
            </div> 
         </div>  
      </div>
<% end %>
<hr>
</div>

app/views/pictures/_show.html.erb
<h2 class="center-block title-1 title-1-about-us " style="float: none" id="photos">
			<%= t('photogallery.title') %></h2>
<div class="container" style="float: none">
	<div class="row" style="float: none">
		<% @pictures.each do |picture| %>
			<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 photogallery">
					<%= link_to image_tag(picture.image.url, :size => "260x180"),
							picture.image.url,
					class: "grouped_elements", rel: "gallery1" %>
			</div>
		<% end %>
	</div>
</div>

app/views/pictures/edit.html.erb
<h1>Изменить фото</h1>
 
<%= form_for :picture, url: picture_path(@picture), method: :patch do |f| %>
   <div class="container">
      <div class="row col-lg-12">
         <div class="col-lg-3">
            <%= f.label "Изображение" %><%= f.file_field :image %>
          </div>
      </div>   
   </div>
   <%= f.submit "Сохранить" %>
<% end %>
 
<%= link_to 'Назад', manager_path %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1><-----------------></h1>